export const EFFECTS = {
  FROM_TO: "fromTo",
  GLOBAL_FROM_TO: "globalFromTo",
};

export const GLOBAL_UPDATABLES = {
  CAMERA_INSTANCE: "camera.instance",
};

export const INSTANCE_NAMES = {
  JIMBO_INTRO_TITLE: "JIMBO_INTRO_TITLE",
  LIGHT_1: "LIGHT_1",
  // LIGHT_2: "LIGHT_2",
  CAMERA: "CAMERA",
  GLOBE: "GLOBE",
  BACKGROUND: "BACKGROUND",
  FLAG: "FLAG",
  SECTION_A_PHRASE_1: "SECTION_A_PHRASE_1",
  SECTION_A_PHRASE_2: "SECTION_A_PHRASE_2",
  SECTION_A_PHRASE_3: "SECTION_A_PHRASE_3",
  SECTION_A_PHRASE_4: "SECTION_A_PHRASE_4",
  SECTION_A_PHRASE_5: "SECTION_A_PHRASE_5",
  SECTION_A_PHRASE_6: "SECTION_A__PHRASE_6",
  SECTION_A_PHRASE_7: "SECTION_A__PHRASE_7",
  SECTION_A_AD_LIBS_FOR_YOU_A: "SECTION_A_AD_LIBS_FOR_YOU_A",
  SECTION_A_AD_LIBS_FOR_YOU_B: "SECTION_A_AD_LIBS_FOR_YOU_B",
  SECTION_B_PHRASE_1: "SECTION_B_PHRASE_1",
  SECTION_B_PHRASE_2: "SECTION_B_PHRASE_2",
  BACKGROUND_SKIN_1: "BACKGROUND_SKIN_1",
  BACKGROUND_SKIN_2: "BACKGROUND_SKIN_2",
  CROSS: "CROSS",
  WITHERBERRY_LOGO: "WITHERBERRY_LOGO",
  LINE_1: "LINE_1",
  LINE_2: "LINE_2",
};
